/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author silvi
 */
public class Controles extends javax.swing.JPanel {

    /**
     * Creates new form Controles
     */
    public Controles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Dado = new javax.swing.JButton();
        Reinicio = new javax.swing.JButton();
        Menu1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Dado.setBackground(new java.awt.Color(0, 102, 102));
        Dado.setForeground(new java.awt.Color(255, 255, 255));
        Dado.setText("Dado");
        Dado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Dado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DadoActionPerformed(evt);
            }
        });
        add(Dado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 43, 60, -1));

        Reinicio.setBackground(new java.awt.Color(0, 102, 102));
        Reinicio.setForeground(new java.awt.Color(255, 255, 255));
        Reinicio.setText("Reinicio");
        Reinicio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Reinicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReinicioActionPerformed(evt);
            }
        });
        add(Reinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 60, -1));

        Menu1.setBackground(new java.awt.Color(0, 102, 102));
        Menu1.setForeground(new java.awt.Color(255, 255, 255));
        Menu1.setText("Menu");
        Menu1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Menu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu1ActionPerformed(evt);
            }
        });
        add(Menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 60, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Contador");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 97, 219, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("8");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 131, 17, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Captura de pantalla 2025-10-19 202416.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void DadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DadoActionPerformed

    private void ReinicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReinicioActionPerformed
        // TODO add your handling code here:
                GUIInicio Inicio =new GUIInicio();
  Inicio.setVisible(true);
  Inicio.setLocationRelativeTo(null);
  this.setVisible(false);
    }//GEN-LAST:event_ReinicioActionPerformed

    private void Menu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Menu1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dado;
    private javax.swing.JButton Menu1;
    private javax.swing.JButton Reinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
