/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author silvi
 */
public class GUIInicio extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        JbtnCreditos = new javax.swing.JButton();
        JbtnInstrucciones = new javax.swing.JButton();
        JbtnHistoria1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/boton.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, -1, -1));

        jComboBox1.setBackground(new java.awt.Color(0, 153, 153));
        jComboBox1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Verde", "Amarillo" }));
        jComboBox1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 100, 30));

        JbtnCreditos.setBackground(new java.awt.Color(0, 153, 153));
        JbtnCreditos.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        JbtnCreditos.setText("Creditos");
        JbtnCreditos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbtnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCreditosActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnCreditos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 80, 30));

        JbtnInstrucciones.setBackground(new java.awt.Color(0, 153, 153));
        JbtnInstrucciones.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        JbtnInstrucciones.setText("Instrucciones");
        JbtnInstrucciones.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbtnInstrucciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnInstruccionesActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnInstrucciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 30));

        JbtnHistoria1.setBackground(new java.awt.Color(0, 153, 153));
        JbtnHistoria1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        JbtnHistoria1.setText("Historia");
        JbtnHistoria1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbtnHistoria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnHistoria1ActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnHistoria1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/imgInicio_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnInstruccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnInstruccionesActionPerformed
        // TODO add your handling code here:
        GUIInstrucciones Instrucciones =new GUIInstrucciones();
  Instrucciones.setVisible(true);
  Instrucciones.setLocationRelativeTo(null);
  this.setVisible(false);
    }//GEN-LAST:event_JbtnInstruccionesActionPerformed

    private void JbtnHistoria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnHistoria1ActionPerformed
        // TODO add your handling code here:
        GUIHistoria Historia =new GUIHistoria();
  Historia.setVisible(true);
  Historia.setLocationRelativeTo(null);
  this.setVisible(false);
    }//GEN-LAST:event_JbtnHistoria1ActionPerformed

    private void JbtnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCreditosActionPerformed
        // TODO add your handling code here:
        GUICreditos Creditos =new GUICreditos();
  Creditos.setVisible(true);
  Creditos.setLocationRelativeTo(null);
  this.setVisible(false); 
    }//GEN-LAST:event_JbtnCreditosActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          Juego tablero =new Juego();
  tablero.setVisible(true);
  tablero.setLocationRelativeTo(null);
  this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnCreditos;
    private javax.swing.JButton JbtnHistoria1;
    private javax.swing.JButton JbtnInstrucciones;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
