/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author silvi
 */
public class GUIInstrucciones extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInstrucciones.class.getName());

    /**
     * Creates new form GUIInstrucciones
     */
    public GUIInstrucciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnMenu = new javax.swing.JButton();
        Texto = new javax.swing.JLabel();
        JblHoja = new javax.swing.JLabel();
        JblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnMenu.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        JbtnMenu.setText("Menu");
        JbtnMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JbtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnMenuActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 90, 30));

        Texto.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        Texto.setText("Texto Pendiente");
        jPanel1.add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        JblHoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hoja.jpg"))); // NOI18N
        jPanel1.add(JblHoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 600, 340));

        JblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/madera.jpg"))); // NOI18N
        jPanel1.add(JblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnMenuActionPerformed
        // TODO add your handling code here:
        GUIInicio Inicio =new GUIInicio();
  Inicio.setVisible(true);
  Inicio.setLocationRelativeTo(null);
  this.setVisible(false);
    }//GEN-LAST:event_JbtnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JblFondo;
    private javax.swing.JLabel JblHoja;
    private javax.swing.JButton JbtnMenu;
    private javax.swing.JLabel Texto;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
